### ISSUE TITLE
Remove reference to Cloud debugger API in bidding_auction_services_gcp_guide.md

### ISSUE THREAD

**Issue by roscoejp** [privacysandbox/protected-auction-services-docs#113]
Cloud Debugger was [deprecated in May 2023](https://cloud.google.com/stackdriver/docs/deprecations/debugger-deprecation), but the [bidding_auction_services_gcp_guide.md](https://github.com/privacysandbox/protected-auction-services-docs/blob/main/bidding_auction_services_gcp_guide.md) document still references it in the API list despite it no longer being available.

```
$ gcloud services list --project ps-dev-pa-baservers-978b | grep de                                                                                                          
confidentialcomputing.googleapis.com  Confidential Computing API
```

**Comment by chatterjee-priyanka** [comment]
Hi @dankocoj-google, would you be able to help update the B&A GCP explainer and also address this issue? Thanks.

**Comment by dankocoj-google** [comment]
Thanks for reporting this Roscoe.
https://github.com/privacysandbox/protected-auction-services-docs/pull/123
