### ISSUE TITLE
Bidding and Auction support for Private Aggregation

### ISSUE THREAD

**Issue by dmdabbs** [privacysandbox/protected-auction-services-docs#44]
[Private Aggregation API](https://github.com/patcg-individual-drafts/private-aggregation-api/) is accessible from Protected Audience API on-device model bidding, scoring and reporting scripts.

What of support in Bidding and Auction?

**Comment by chatterjee-priyanka** [comment]
We plan to support this and make it available sometime in H1 2023. 

cc- @adigupt09.

**Comment by kevinkiklee** [comment]
This issue has been migrated to the new [WICG/protected-auction-services-discussion](https://github.com/WICG/protected-auction-services-discussion/issues/12) repository. 

Please continue the discussion in the migrated issue here: https://github.com/WICG/protected-auction-services-discussion/issues/15
