### ISSUE TITLE
B & A Timelines and Details w/r/t 1% Ramp Up

### ISSUE THREAD

**Issue by thegreatfatzby** [privacysandbox/protected-auction-services-docs#55]
Couple of questions came up after some internal discussion about TEE usage for the 1% period starting Jan 1 2024:

**BA GA Timing**
BA timing is currently Alpha starting already, beta in October, Scale Testing Feb 24. Chrome browsers will start the 1% deprecation on Jan 1 2024. Having been a math major, I can proudly state with a high level of certainty that Jan 1 2024 < Feb 2024.

What is the thinking/guidance here? I see many features should be ready during beta, but given the reasons for moving to BA (which we are wholly behind) the BA availability coming after the deprecation is something I'd like to understand better.

**Opted In Flag**
From the [guidance to sellers](https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_api.md#guidance-to-sellers--ssps) I see a couple of indications that a flag will be sent from the client to Seller Ad Service, indicating whether the browser is part of the experiment (in particular see `Chrome browser will support a flag. Users' browsers that enable the flag can be targeted.` and `Set up experiments for ad auctions and target user opt-in traffic.`). I'm hoping to get a touch more detail on that as I see that conflicting with some of the signaling-of-opt-in/out discussion [here](https://github.com/WICG/turtledove/issues/335#issuecomment-1572276886).

Will this flag:

- Indicate: 3PC deprecation? Fledge enablement? Or both?
- Be available for the duration of the ramp up period?
- Be available after the ramp up period to indicate opt-outs (Fledge disablement?).

**Comment by thegreatfatzby** [comment]
Hey @chatterjee-priyanka @pauljen can you confirm my understanding about the first point (BA GA Timing) here, that the BA team does not recommend using BA servers in production for the 1% part B testing starting on January 1st, and that that the recommendation is to use client side PAAPI for now?

Also would appreciate any available confirmation on the opted in flag, but can decouple that.

**Comment by chatterjee-priyanka** [comment]
This is the most upto-date B&A timeline and roadmap: https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_api.md#timeline-and-roadmap

Thanks.

**Comment by kevinkiklee** [comment]
This issue has been migrated to the new [WICG/protected-auction-services-discussion](https://github.com/WICG/protected-auction-services-discussion/issues/12) repository. 

Please continue the discussion in the migrated issue here: https://github.com/WICG/protected-auction-services-discussion/issues/18
