### ISSUE TITLE
BA Traffic Shaping (QPS, etc) and Configuration Between Sellers and Buyers

### ISSUE THREAD

**Issue by thegreatfatzby** [privacysandbox/protected-auction-services-docs#57]
Are any knobs for shaping and configuring traffic between an SSP and DSP being discussed? In particular I'd think allowing some filters for traffic flowing from the SFE to BFEs would be good, as we [currently support different types of filters](https://docs.xandr.com/bundle/xandr-bidders/page/bidder-profile-migration-guide.html) when sending requests to DSPs to help them manage their traffic and infrastructure. We also allow a bidder to change the location of their DSP collection per DC without requiring a restart on our side.

QPS or other throttling controls are valuable. Our simplest ones are QPS per data center but we do some interesting stuff with dynamically optimizing the bidstream based on auction results or server failure/timeouts (Hystrix'y type stuff). From what I can see so far in the [SFE Runtime Flags](https://github.com/privacysandbox/bidding-auction-servers/blob/main/services/seller_frontend_service/runtime_flags.h) I'm not seeing anything that seems related to traffic. I do see configurations related to auto-scaling, and that is good, but not all ad techs will want to auto-scale as high as traffic allows, and even with good and infinite auto-scaling in place static and dynamic QPS throttles are still valuable in maintaining a working system.

Additionally on BFE cluster config, am I right that, as of now, if a DSP wanted to change the location of their cluster, they'd have to ask the SSP to restart all of their SFEs with a new config with BFE hosts? And they'd have to do that across any sellers they expect traffic from?

**Comment by kevinkiklee** [comment]
This issue has been migrated to the new [WICG/protected-auction-services-discussion](https://github.com/WICG/protected-auction-services-discussion/issues/12) repository. 

Please continue the discussion in the migrated issue here: https://github.com/WICG/protected-auction-services-discussion/issues/20
