### ISSUE TITLE
Create Coloring Consistency Across Multiple Dimensions!!! Untrusted vs Trusted Color VS Entities Distinction via Other Visual Signals

### ISSUE THREAD

**Issue by thegreatfatzby** [privacysandbox/protected-auction-services-docs#58]
Fwends, I have a diagram coloring request, and yes I'm being super [cereal](https://www.youtube.com/watch?v=nGf3PdZviXk). 

One of the critical distinctions when thinking about PPA through B&A is understanding the environment that something is happening in, for instance client, vs your own servers, vs a TEE. We also of course have multiple entities to deal with. 

In the [main diagram](https://github.com/privacysandbox/fledge-docs/blob/main/images/unified-contextual-remarketing-bidding-auction-services.png) we see background color choice by env type and not by entity, text always black:
- Red = client
- Yellow = untrusted (your servers)
- Green = TEE

In [this](https://github.com/privacysandbox/fledge-docs/blob/main/images/ba-system-seq-11.png) one from [this](https://github.com/privacysandbox/fledge-docs/blob/main/images/ba-system-seq-11.png) section in the main explainer I see background coloring by entity and not env type, text always black:
- Red = Client
- Green = Seller, TEE or Untrusted
- Blue = Buyer1
- Grey = Buyer2

In [this](https://github.com/privacysandbox/fledge-docs/blob/main/images/ba-system-seq-11.png) one from [this](https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_multi_seller_auctions.md#sequence-diagram) section of the multi seller, we see background coloring by entity and not env type, text always black:
- Red = Client
- Blue = Seller 1, trusted/untrusted
- Green = Seller 2, trusted/untrusted

My fwends! It would help me, and I wonder if others, if we could Create Coloring Consistency across Multiple Dimensions. I think it will help people to understand the envs _**and**_ entities if we do something like:
- Use background color for environment, as done in the main diagram (yellow=untrusted, green=tee, red=client), do this consistently across diagrams.
- Use text color for entities, this can be diagram specific.

**Comment by thegreatfatzby** [comment]
I appreciate the fast response, as ever I am happy to help.

**Comment by kevinkiklee** [comment]
This issue has been migrated to the new [WICG/protected-auction-services-discussion](https://github.com/WICG/protected-auction-services-discussion/issues/12) repository. 

Please continue the discussion in the migrated issue here: https://github.com/WICG/protected-auction-services-discussion/issues/21
