### ISSUE TITLE
IG Execution Mode Impact in Bidding Service

### ISSUE THREAD

**Issue by thegreatfatzby** [privacysandbox/protected-auction-services-docs#59]
Will the Bidding Service worklet execution work as described [here](https://github.com/WICG/turtledove/blob/main/FLEDGE.md#12-interest-group-attributes) w/r/t to the `executionMode`s?

**Comment by chatterjee-priyanka** [comment]
Hey,

Thanks for opening the issue.

* If you are referring to Priority Vector:
DSPs can set the priority in Interest Groups; B&A recommends setting the priority for payload optimization: https://github.com/privacysandbox/fledge-docs/blob/main/bidding-auction-services-payload-optimization.md#higher-priority-interest-groups-sent-from-the-device. However, Priority Vector (dot product) needs to be done in TEE based BuyerFrontEnd. This an optimization that B&A plans to support that.

This section of the B&A explainer will be kept updated about timelines / roadmap: https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_api.md#timeline-and-roadmap. 

* Execution in Bidding service: https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_system_design.md#code-execution

**Comment by kevinkiklee** [comment]
This issue has been migrated to the new [WICG/protected-auction-services-discussion](https://github.com/WICG/protected-auction-services-discussion/issues/12) repository. 

Please continue the discussion in the migrated issue here: https://github.com/WICG/protected-auction-services-discussion/issues/22
