### ISSUE TITLE
Reporting Happens Server Side

### ISSUE THREAD

**Issue by thegreatfatzby** [privacysandbox/protected-auction-services-docs#60]
Hey fwends, I'm hoping for clarification on reportWin/reportResult in BA. Is this correct:

```
ReportWin() will be executed in Auction service, reporting url for the buyer and registered ad beacons (for Fenced Frame reporting) would be generated in Auction service and returned to the client in encrypted [AuctionResult](https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_api.md#auctionresult). The client will ping the buyer's reporting endpoint using the reporting url.

Note: A detailed design covering reporting will be published separately.
```

How will this work in the case that a BA auction is part of a multi-component auction that is occurring on the client, something prebid like, where the client would have a contextual bid it needs to evaluate it might not get prior to the private auction?

**Comment by chatterjee-priyanka** [comment]
Hey, 

To support reporting for device orchestrated component auction, the contextual signals for the winning buyer (and seller) of each component level auction will be sent back to the client / browser. Then on the browser, after the top level auction and ad is rendered,  reportResult() for the winning seller and reportWin() for the winning buyer will be executed to generate the urls. Then the reporting pings to adtech's reporting endpoints will happen from the client / browser.

Thanks,
Priyanka

**Comment by kevinkiklee** [comment]
This issue has been migrated to the new [WICG/protected-auction-services-discussion](https://github.com/WICG/protected-auction-services-discussion/issues/12) repository. 

Please continue the discussion in the migrated issue here: https://github.com/WICG/protected-auction-services-discussion/issues/23
