### ISSUE TITLE
Supporting of experimentGroupId

### ISSUE THREAD

**Issue by yanushP** [privacysandbox/protected-auction-services-docs#80]
Hi @chatterjee-priyanka 

Do you planning to support field `experimentGroupId` in B&A code and in request to KeyValue service from BuyerFrontEnd? 
 
Because you docs saying that it will be supported [here](https://github.com/privacysandbox/fledge-docs/blob/999bc459c91ef4bc850d2f78339b083d458a40e9/bidding_auction_services_api.md#buyer-byos-keyvalue-service).
However, I don't see that it's supported in code [here](https://github.com/privacysandbox/bidding-auction-servers/blob/b27547a55f20021eb91e1e61b0d2175b4aee02ea/services/common/clients/http_kv_server/buyer/buyer_key_value_async_http_client.h#L38) or [here](https://github.com/privacysandbox/bidding-auction-servers/blob/b27547a55f20021eb91e1e61b0d2175b4aee02ea/services/common/clients/http_kv_server/buyer/buyer_key_value_async_http_client.cc#L29C1-L61C1).
At the same time, it's already supported in on-device version, in chromium [here](https://github.com/chromium/chromium/blob/215d235344a022ff753a37791796c06aabb0423f/content/services/auction_worklet/trusted_signals.cc#L377-L381). 

Could you please confirm that this field will be supported in future? The running of experiments it's important for us.

**Comment by chatterjee-priyanka** [comment]
Hi @yanushP 

B&A currently doesn't have the support for `experimentGroupId`, but aims to roll this out by the end of January 2024 (I would explicitly note that in https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_api.md#beta-2-february-2024). Let us know if end of Jan '2024 would be too late. 

However, B&A SelectAd API includes the required fields:

- The `buyer_kv_experiment_group_id` can be passed in RTB response to the seller's ad server. The seller's ad server can pass that in SelectAdRequest.AuctionConfig.PerBuyerConfig, refer to the [field](https://github.com/privacysandbox/bidding-auction-servers/blob/b27547a55f20021eb91e1e61b0d2175b4aee02ea/api/bidding_auction_servers.proto#L341). 

- The `seller_kv_experiment_group_id` can be set by the seller's ad server in SelectAdRequest.AuctionConfig. Refer to the [field](https://github.com/privacysandbox/bidding-auction-servers/blob/b27547a55f20021eb91e1e61b0d2175b4aee02ea/api/bidding_auction_servers.proto#L397).

The API changes to GetBids and propagating these for seller / buyer kv lookups are pending work.

_Note: The above links should be stable._

**Comment by kevinkiklee** [comment]
This issue has been migrated to the new [WICG/protected-auction-services-discussion](https://github.com/WICG/protected-auction-services-discussion/issues/12) repository. 

Please continue the discussion in the migrated issue here: https://github.com/WICG/protected-auction-services-discussion/issues/25
